### PR TITLE
Synchronous start

### PR DESCRIPTION
**Pull request by akoutmos**

### CODE REVIEW

**Review by bryannaegele — APPROVED** [review]

**Comment by bryannaegele** [comment]
Thanks @akoutmos!

**Comment by akoutmos** [comment]
Of course! Any thoughts on when a new version will be published to Hex? Would love to remove the copy and pasted version of this lib in PromEx :D.

**Comment by bryannaegele** [comment]
Done

**Comment by akoutmos** [comment]
Thank a bunch!!!!

**Pull request merged**
